version: "3.8"

services:
    mysql:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        container_name: mysql

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: redis

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - mysql
            - redis
        volumes:
            - .:/var/www/html
        container_name: laravel

    node:
        image: node:latest
        working_dir: /var/www/html
        command: sh -c "npm install && npm run dev"
        depends_on:
            - laravel
        volumes:
            - .:/var/www/html
        container_name: node
